services:
  - type: web
    name: novaoptionsbot
    runtime: node
    plan: starter
    autoDeploy: true
    buildCommand: bun install && bun run build
    startCommand: bun start
    buildFilter:
      paths:
        - src/*.ts
        - src/*.js
        - src/**/*.ts
        - src/**/*.js
        - src/**/*.md
    envVars:
      - fromGroup: novaoptionsbot
