services:
  - type: web
    name: novaoptionsbot
    runtime: node
    plan: starter
    autoDeploy: true
    buildCommand: bun install && bun run build
    startCommand: node dist/dist/index.js
    envVars:
      - fromGroup: novaoptionsbot
      - key: TZ
        value: Africa/Lagos
      - key: DATABASE_URL
        fromDatabase:
          name: novaoptionsbot
          property: connectionString
databases:
  - name: novaoptionsbot
    user: admin
    plan: basic-256mb
